# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobSpec(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'allow_non_restored_state': 'bool',
        'artifact': 'Artifact',
        'deployment_target': 'JobDeploymentTarget',
        'flink_configuration': 'dict(str, str)',
        'kubernetes': 'KubernetesOptions',
        'logging': 'Logging',
        'number_of_task_managers': 'int',
        'parallelism': 'int',
        'resources': 'dict(str, ResourceSpec)',
        'savepoint_location': 'URI'
    }

    attribute_map = {
        'allow_non_restored_state': 'allowNonRestoredState',
        'artifact': 'artifact',
        'deployment_target': 'deploymentTarget',
        'flink_configuration': 'flinkConfiguration',
        'kubernetes': 'kubernetes',
        'logging': 'logging',
        'number_of_task_managers': 'numberOfTaskManagers',
        'parallelism': 'parallelism',
        'resources': 'resources',
        'savepoint_location': 'savepointLocation'
    }

    def __init__(self, allow_non_restored_state=None, artifact=None, deployment_target=None, flink_configuration=None, kubernetes=None, logging=None, number_of_task_managers=None, parallelism=None, resources=None, savepoint_location=None):  # noqa: E501
        """JobSpec - a model defined in Swagger"""  # noqa: E501

        self._allow_non_restored_state = None
        self._artifact = None
        self._deployment_target = None
        self._flink_configuration = None
        self._kubernetes = None
        self._logging = None
        self._number_of_task_managers = None
        self._parallelism = None
        self._resources = None
        self._savepoint_location = None
        self.discriminator = None

        if allow_non_restored_state is not None:
            self.allow_non_restored_state = allow_non_restored_state
        if artifact is not None:
            self.artifact = artifact
        if deployment_target is not None:
            self.deployment_target = deployment_target
        if flink_configuration is not None:
            self.flink_configuration = flink_configuration
        if kubernetes is not None:
            self.kubernetes = kubernetes
        if logging is not None:
            self.logging = logging
        if number_of_task_managers is not None:
            self.number_of_task_managers = number_of_task_managers
        if parallelism is not None:
            self.parallelism = parallelism
        if resources is not None:
            self.resources = resources
        if savepoint_location is not None:
            self.savepoint_location = savepoint_location

    @property
    def allow_non_restored_state(self):
        """Gets the allow_non_restored_state of this JobSpec.  # noqa: E501


        :return: The allow_non_restored_state of this JobSpec.  # noqa: E501
        :rtype: bool
        """
        return self._allow_non_restored_state

    @allow_non_restored_state.setter
    def allow_non_restored_state(self, allow_non_restored_state):
        """Sets the allow_non_restored_state of this JobSpec.


        :param allow_non_restored_state: The allow_non_restored_state of this JobSpec.  # noqa: E501
        :type: bool
        """

        self._allow_non_restored_state = allow_non_restored_state

    @property
    def artifact(self):
        """Gets the artifact of this JobSpec.  # noqa: E501


        :return: The artifact of this JobSpec.  # noqa: E501
        :rtype: Artifact
        """
        return self._artifact

    @artifact.setter
    def artifact(self, artifact):
        """Sets the artifact of this JobSpec.


        :param artifact: The artifact of this JobSpec.  # noqa: E501
        :type: Artifact
        """

        self._artifact = artifact

    @property
    def deployment_target(self):
        """Gets the deployment_target of this JobSpec.  # noqa: E501


        :return: The deployment_target of this JobSpec.  # noqa: E501
        :rtype: JobDeploymentTarget
        """
        return self._deployment_target

    @deployment_target.setter
    def deployment_target(self, deployment_target):
        """Sets the deployment_target of this JobSpec.


        :param deployment_target: The deployment_target of this JobSpec.  # noqa: E501
        :type: JobDeploymentTarget
        """

        self._deployment_target = deployment_target

    @property
    def flink_configuration(self):
        """Gets the flink_configuration of this JobSpec.  # noqa: E501


        :return: The flink_configuration of this JobSpec.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._flink_configuration

    @flink_configuration.setter
    def flink_configuration(self, flink_configuration):
        """Sets the flink_configuration of this JobSpec.


        :param flink_configuration: The flink_configuration of this JobSpec.  # noqa: E501
        :type: dict(str, str)
        """

        self._flink_configuration = flink_configuration

    @property
    def kubernetes(self):
        """Gets the kubernetes of this JobSpec.  # noqa: E501


        :return: The kubernetes of this JobSpec.  # noqa: E501
        :rtype: KubernetesOptions
        """
        return self._kubernetes

    @kubernetes.setter
    def kubernetes(self, kubernetes):
        """Sets the kubernetes of this JobSpec.


        :param kubernetes: The kubernetes of this JobSpec.  # noqa: E501
        :type: KubernetesOptions
        """

        self._kubernetes = kubernetes

    @property
    def logging(self):
        """Gets the logging of this JobSpec.  # noqa: E501


        :return: The logging of this JobSpec.  # noqa: E501
        :rtype: Logging
        """
        return self._logging

    @logging.setter
    def logging(self, logging):
        """Sets the logging of this JobSpec.


        :param logging: The logging of this JobSpec.  # noqa: E501
        :type: Logging
        """

        self._logging = logging

    @property
    def number_of_task_managers(self):
        """Gets the number_of_task_managers of this JobSpec.  # noqa: E501


        :return: The number_of_task_managers of this JobSpec.  # noqa: E501
        :rtype: int
        """
        return self._number_of_task_managers

    @number_of_task_managers.setter
    def number_of_task_managers(self, number_of_task_managers):
        """Sets the number_of_task_managers of this JobSpec.


        :param number_of_task_managers: The number_of_task_managers of this JobSpec.  # noqa: E501
        :type: int
        """

        self._number_of_task_managers = number_of_task_managers

    @property
    def parallelism(self):
        """Gets the parallelism of this JobSpec.  # noqa: E501


        :return: The parallelism of this JobSpec.  # noqa: E501
        :rtype: int
        """
        return self._parallelism

    @parallelism.setter
    def parallelism(self, parallelism):
        """Sets the parallelism of this JobSpec.


        :param parallelism: The parallelism of this JobSpec.  # noqa: E501
        :type: int
        """

        self._parallelism = parallelism

    @property
    def resources(self):
        """Gets the resources of this JobSpec.  # noqa: E501


        :return: The resources of this JobSpec.  # noqa: E501
        :rtype: dict(str, ResourceSpec)
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this JobSpec.


        :param resources: The resources of this JobSpec.  # noqa: E501
        :type: dict(str, ResourceSpec)
        """

        self._resources = resources

    @property
    def savepoint_location(self):
        """Gets the savepoint_location of this JobSpec.  # noqa: E501


        :return: The savepoint_location of this JobSpec.  # noqa: E501
        :rtype: URI
        """
        return self._savepoint_location

    @savepoint_location.setter
    def savepoint_location(self, savepoint_location):
        """Sets the savepoint_location of this JobSpec.


        :param savepoint_location: The savepoint_location of this JobSpec.  # noqa: E501
        :type: URI
        """

        self._savepoint_location = savepoint_location

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobSpec, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobSpec):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
