# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JobMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'annotations': 'dict(str, str)',
        'created_at': 'datetime',
        'deployment_id': 'str',
        'id': 'str',
        'modified_at': 'datetime',
        'namespace': 'str',
        'resource_version': 'int',
        'terminated_at': 'datetime'
    }

    attribute_map = {
        'annotations': 'annotations',
        'created_at': 'createdAt',
        'deployment_id': 'deploymentId',
        'id': 'id',
        'modified_at': 'modifiedAt',
        'namespace': 'namespace',
        'resource_version': 'resourceVersion',
        'terminated_at': 'terminatedAt'
    }

    def __init__(self, annotations=None, created_at=None, deployment_id=None, id=None, modified_at=None, namespace=None, resource_version=None, terminated_at=None):  # noqa: E501
        """JobMetadata - a model defined in Swagger"""  # noqa: E501

        self._annotations = None
        self._created_at = None
        self._deployment_id = None
        self._id = None
        self._modified_at = None
        self._namespace = None
        self._resource_version = None
        self._terminated_at = None
        self.discriminator = None

        if annotations is not None:
            self.annotations = annotations
        if created_at is not None:
            self.created_at = created_at
        if deployment_id is not None:
            self.deployment_id = deployment_id
        if id is not None:
            self.id = id
        if modified_at is not None:
            self.modified_at = modified_at
        if namespace is not None:
            self.namespace = namespace
        if resource_version is not None:
            self.resource_version = resource_version
        if terminated_at is not None:
            self.terminated_at = terminated_at

    @property
    def annotations(self):
        """Gets the annotations of this JobMetadata.  # noqa: E501


        :return: The annotations of this JobMetadata.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations):
        """Sets the annotations of this JobMetadata.


        :param annotations: The annotations of this JobMetadata.  # noqa: E501
        :type: dict(str, str)
        """

        self._annotations = annotations

    @property
    def created_at(self):
        """Gets the created_at of this JobMetadata.  # noqa: E501


        :return: The created_at of this JobMetadata.  # noqa: E501
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this JobMetadata.


        :param created_at: The created_at of this JobMetadata.  # noqa: E501
        :type: datetime
        """

        self._created_at = created_at

    @property
    def deployment_id(self):
        """Gets the deployment_id of this JobMetadata.  # noqa: E501


        :return: The deployment_id of this JobMetadata.  # noqa: E501
        :rtype: str
        """
        return self._deployment_id

    @deployment_id.setter
    def deployment_id(self, deployment_id):
        """Sets the deployment_id of this JobMetadata.


        :param deployment_id: The deployment_id of this JobMetadata.  # noqa: E501
        :type: str
        """

        self._deployment_id = deployment_id

    @property
    def id(self):
        """Gets the id of this JobMetadata.  # noqa: E501


        :return: The id of this JobMetadata.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this JobMetadata.


        :param id: The id of this JobMetadata.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def modified_at(self):
        """Gets the modified_at of this JobMetadata.  # noqa: E501


        :return: The modified_at of this JobMetadata.  # noqa: E501
        :rtype: datetime
        """
        return self._modified_at

    @modified_at.setter
    def modified_at(self, modified_at):
        """Sets the modified_at of this JobMetadata.


        :param modified_at: The modified_at of this JobMetadata.  # noqa: E501
        :type: datetime
        """

        self._modified_at = modified_at

    @property
    def namespace(self):
        """Gets the namespace of this JobMetadata.  # noqa: E501


        :return: The namespace of this JobMetadata.  # noqa: E501
        :rtype: str
        """
        return self._namespace

    @namespace.setter
    def namespace(self, namespace):
        """Sets the namespace of this JobMetadata.


        :param namespace: The namespace of this JobMetadata.  # noqa: E501
        :type: str
        """

        self._namespace = namespace

    @property
    def resource_version(self):
        """Gets the resource_version of this JobMetadata.  # noqa: E501


        :return: The resource_version of this JobMetadata.  # noqa: E501
        :rtype: int
        """
        return self._resource_version

    @resource_version.setter
    def resource_version(self, resource_version):
        """Sets the resource_version of this JobMetadata.


        :param resource_version: The resource_version of this JobMetadata.  # noqa: E501
        :type: int
        """

        self._resource_version = resource_version

    @property
    def terminated_at(self):
        """Gets the terminated_at of this JobMetadata.  # noqa: E501


        :return: The terminated_at of this JobMetadata.  # noqa: E501
        :rtype: datetime
        """
        return self._terminated_at

    @terminated_at.setter
    def terminated_at(self, terminated_at):
        """Sets the terminated_at of this JobMetadata.


        :param terminated_at: The terminated_at of this JobMetadata.  # noqa: E501
        :type: datetime
        """

        self._terminated_at = terminated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
