# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class Logging(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'log4j_loggers': 'dict(str, str)'
    }

    attribute_map = {
        'log4j_loggers': 'log4jLoggers'
    }

    def __init__(self, log4j_loggers=None):  # noqa: E501
        """Logging - a model defined in Swagger"""  # noqa: E501

        self._log4j_loggers = None
        self.discriminator = None

        if log4j_loggers is not None:
            self.log4j_loggers = log4j_loggers

    @property
    def log4j_loggers(self):
        """Gets the log4j_loggers of this Logging.  # noqa: E501


        :return: The log4j_loggers of this Logging.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._log4j_loggers

    @log4j_loggers.setter
    def log4j_loggers(self, log4j_loggers):
        """Sets the log4j_loggers of this Logging.


        :param log4j_loggers: The log4j_loggers of this Logging.  # noqa: E501
        :type: dict(str, str)
        """

        self._log4j_loggers = log4j_loggers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Logging, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Logging):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
