# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VolumeAndMount(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'volume': 'JsonNode',
        'volume_mount': 'JsonNode'
    }

    attribute_map = {
        'name': 'name',
        'volume': 'volume',
        'volume_mount': 'volumeMount'
    }

    def __init__(self, name=None, volume=None, volume_mount=None):  # noqa: E501
        """VolumeAndMount - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._volume = None
        self._volume_mount = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if volume is not None:
            self.volume = volume
        if volume_mount is not None:
            self.volume_mount = volume_mount

    @property
    def name(self):
        """Gets the name of this VolumeAndMount.  # noqa: E501


        :return: The name of this VolumeAndMount.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this VolumeAndMount.


        :param name: The name of this VolumeAndMount.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def volume(self):
        """Gets the volume of this VolumeAndMount.  # noqa: E501


        :return: The volume of this VolumeAndMount.  # noqa: E501
        :rtype: JsonNode
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this VolumeAndMount.


        :param volume: The volume of this VolumeAndMount.  # noqa: E501
        :type: JsonNode
        """

        self._volume = volume

    @property
    def volume_mount(self):
        """Gets the volume_mount of this VolumeAndMount.  # noqa: E501


        :return: The volume_mount of this VolumeAndMount.  # noqa: E501
        :rtype: JsonNode
        """
        return self._volume_mount

    @volume_mount.setter
    def volume_mount(self, volume_mount):
        """Sets the volume_mount of this VolumeAndMount.


        :param volume_mount: The volume_mount of this VolumeAndMount.  # noqa: E501
        :type: JsonNode
        """

        self._volume_mount = volume_mount

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VolumeAndMount, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VolumeAndMount):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
