# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ververica_api_sdk
from ververica_api_sdk.api.secret_value_resource_api import SecretValueResourceApi  # noqa: E501
from ververica_api_sdk.rest import ApiException


class TestSecretValueResourceApi(unittest.TestCase):
    """SecretValueResourceApi unit test stubs"""

    def setUp(self):
        self.api = ververica_api_sdk.api.secret_value_resource_api.SecretValueResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_secret_value_using_post(self):
        """Test case for create_secret_value_using_post

        Create a secret value  # noqa: E501
        """
        pass

    def test_delete_secret_value_using_delete(self):
        """Test case for delete_secret_value_using_delete

        Delete a secret value  # noqa: E501
        """
        pass

    def test_get_secret_value_using_get(self):
        """Test case for get_secret_value_using_get

        Get a secret value by name  # noqa: E501
        """
        pass

    def test_get_secret_values_using_get(self):
        """Test case for get_secret_values_using_get

        List all secrets values  # noqa: E501
        """
        pass

    def test_update_secret_value_using_patch(self):
        """Test case for update_secret_value_using_patch

        Update a secret value  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
