# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ververica_api_sdk
from ververica_api_sdk.api.event_resource_api import EventResourceApi  # noqa: E501
from ververica_api_sdk.rest import ApiException


class TestEventResourceApi(unittest.TestCase):
    """EventResourceApi unit test stubs"""

    def setUp(self):
        self.api = ververica_api_sdk.api.event_resource_api.EventResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_events_using_get(self):
        """Test case for get_events_using_get

        Filter all events for a deployment or job  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
