# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ververica_api_sdk
from ververica_api_sdk.api.savepoint_resource_api import SavepointResourceApi  # noqa: E501
from ververica_api_sdk.rest import ApiException


class TestSavepointResourceApi(unittest.TestCase):
    """SavepointResourceApi unit test stubs"""

    def setUp(self):
        self.api = ververica_api_sdk.api.savepoint_resource_api.SavepointResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_savepoint_using_post(self):
        """Test case for create_savepoint_using_post

        Create a new savepoint  # noqa: E501
        """
        pass

    def test_get_savepoint_using_get(self):
        """Test case for get_savepoint_using_get

        Get a savepoint by id  # noqa: E501
        """
        pass

    def test_get_savepoints_using_get(self):
        """Test case for get_savepoints_using_get

        List all savepoints. Can be filtered by DeploymentId  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
