# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ververica_api_sdk
from ververica_api_sdk.api.status_resource_api import StatusResourceApi  # noqa: E501
from ververica_api_sdk.rest import ApiException


class TestStatusResourceApi(unittest.TestCase):
    """StatusResourceApi unit test stubs"""

    def setUp(self):
        self.api = ververica_api_sdk.api.status_resource_api.StatusResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_status_using_get(self):
        """Test case for get_status_using_get

        Check that the server is running  # noqa: E501
        """
        pass

    def test_get_system_info_using_get(self):
        """Test case for get_system_info_using_get

        Get system's information  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
