# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ververica_api_sdk
from ververica_api_sdk.api.job_resource_api import JobResourceApi  # noqa: E501
from ververica_api_sdk.rest import ApiException


class TestJobResourceApi(unittest.TestCase):
    """JobResourceApi unit test stubs"""

    def setUp(self):
        self.api = ververica_api_sdk.api.job_resource_api.JobResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_job_using_get(self):
        """Test case for get_job_using_get

        Get a job by id  # noqa: E501
        """
        pass

    def test_get_jobs_using_get(self):
        """Test case for get_jobs_using_get

        List all jobs. Can be filtered by DeploymentId  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
