# coding: utf-8

"""
    Application Manager API

    Application Manager APIs to control Apache Flink jobs  # noqa: E501

    OpenAPI spec version: 2.0.1
    Contact: platform@ververica.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import ververica_api_sdk
from ververica_api_sdk.models.deployment import Deployment  # noqa: E501
from ververica_api_sdk.rest import ApiException


class TestDeployment(unittest.TestCase):
    """Deployment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeployment(self):
        """Test Deployment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ververica_api_sdk.models.deployment.Deployment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
